name: dart_ari_proxy
description: Asterisk PBX Rest Interface in Dart
version: 1.0.0
repository: https://github.com/kellykinyama12/dart-ari-proxy

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  dotenv: ^4.2.0
  eventify: ^1.0.1
  events_emitter: ^0.5.2
  redis: ^4.0.0
  uuid: ^4.3.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
